import { FilterOption } from './types';

export const FILTERS: FilterOption[] = [
  { id: 'photo_pro', name: 'Photo Pro', prompt: 'A professionally shot photograph with perfect lighting, composition, and focus. Recreate the scene from the original image, but elevate it to the quality of a high-end magazine shoot. The lighting should be soft and flattering, the colors vibrant and balanced, and the background subtly blurred to draw attention to the subject. The final result should look realistic, sharp, and impeccably polished.', humorousDescription: "Makes your photo look like it was taken by someone who actually knows what they're doing." },
  { id: 'claymation', name: 'Claymation', prompt: 'A charming scene in the stop-motion style of Aardman Animation. Subjects and environment must be meticulously crafted from plasticine clay, featuring a textured, handcrafted look with visible fingerprints and tool marks. The lighting should be practical and warm, as if on a miniature studio set.', humorousDescription: "Turns everything into lumpy, charming clay. Don't leave it in the sun." },
  { id: 'vintage_comic', name: 'Vintage Comic', prompt: 'A panel from a 1960s vintage comic book. It is CRITICAL to preserve the exact subject, pose, and composition from the original image. Transform the scene using the classic vintage comic aesthetic: apply bold, heavy black ink outlines, a limited CMYK color palette, visible Ben-Day dots for shading, and an overall yellowed, pulp paper texture.', humorousDescription: "BAM! POW! Your photo, now with more dots and questionable color choices from the 60s." },
  { id: 'color_vibe', name: 'Color Vibe', prompt: 'CRITICAL: Transform the person in the photo into a Pop Art portrait in the style of Roy Lichtenstein. DO NOT create a new, realistic person. The final image MUST have thick black outlines, oversized Ben-Day dots for all shading, and use a palette of bold, primary colors. The subject\'s exact pose and composition from the original image must be preserved. The background should be a single, solid, bright color.', humorousDescription: "It's Pop Art, darling! Prepare for bold colors and a sudden urge to say 'Whaam!'" },
  { id: 'neon_cyberpunk', name: 'Neon Cyberpunk', prompt: 'An over-the-top, 80s retro-futuristic cyberpunk scene. It is critical that you recreate the subject\'s exact pose, action, and direction from the original image. With that pose maintained, transform the subject with fun and slightly ridiculous cybernetics like a glowing laser visor or robotic arms. Their clothing should be a mix of punk and chrome. Place them in a rain-slicked, neon-drenched cityscape at night, lit by vibrant blues and pinks. The style should be bold, cheesy, and fun, straight off the cover of a vintage sci-fi VHS tape.', humorousDescription: "Your photo, but it just watched Blade Runner on a loop. Expect chrome, neon, and questionable 80s fashion." },
  { id: 'bw_photo', name: 'Black & White Photo', prompt: 'CRITICAL: The generated image MUST be in black and white. Absolutely no color. Convert the scene into a dramatic, high-contrast black and white photograph in the style of Ansel Adams. Discard all color information from the original image. The final output must emphasize deep, rich blacks, brilliant highlights, and a full range of mid-tones (chiaroscuro), focusing on texture, form, and dramatic lighting.', humorousDescription: "For when you're feeling deep and artsy. Or just want to hide that the colors were weird." },
  { id: 'low_poly', name: 'Low Poly 3D', prompt: 'A low-poly 3D artwork. The entire scene must be rendered with large, visible, geometric polygons (triangles and quads), resulting in an angular, faceted, and non-realistic look with flat shading. Crucially, preserve the original color palette and mood of the photo. If the original is black and white, the low-poly version must also be black and white. If the input image appears to be a composite or contains multiple panels, identify and restyle only the primary human figure.', humorousDescription: "Like your photo was rendered on a potato-powered computer from 1995. All sharp edges." },
  { id: '3d_character', name: '3D Character', prompt: 'CRITICAL: Do NOT create a photorealistic human. Instead, transform the subject into a stylized 3D character from a modern animated feature film like those from Pixar or DreamWorks. The character must have appealing, exaggerated proportions, large expressive eyes, and artistically rendered skin and hair (not realistic). Pay close attention to text or logos on clothing and reproduce them accurately. The lighting should be a professional three-point studio setup, creating soft shadows and highlights that emphasize the character\'s stylized form.', humorousDescription: "Casts your subject in the next big animated movie. Warning: may result in giant, adorable eyes." },
];